name: Tournament
main: work.mgnet.Tournament
version: 1.0
api-version: 1.17
website: mgnet.work
description: Y u here?
authors: [MCPfannkuchenYT]
database: false
commands:
  start: 
    usage: /start <game>
  endTournament:
    usage: /endTournament
  generateTournament:
    usage: /generateTournament
  nextGame:
    usage: /nextGame
  ticks:
    description: Changes the Tickrate
    aliases: [tickrate, tickratechanger]
    permission: work.mgnet.ticks
    usage: "Usage: /ticks (default) [tickrate]"