name: AdvancedLobby
version: 1.3
authors: [cyne, Pancake]
main: de.cyne.advancedlobby.AdvancedLobby
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  advancedlobby:
    description: 'Main command of AdvancedLobby'
    aliases: al
  build:
    description: 'Build command'
    aliases: edit
  chatclear:
    description: 'ChatClear command'
    aliases: cc
  fly:
    description: 'Fly command'
  gamemode:
    description: 'GameMode command'
    aliases: gm
  globalmute:
    description: 'GlobalMute command'
    aliases: gmute
  lobby:
    description: 'Lobby command'
    aliases: [hub, l]
  teleportall:
    description: 'TeleportAll command'
    aliases: tpall

permissions:
  advancedlobby.*:
    children:
      advancedlobby.commands.*: true
      advancedlobby.gadgets.*: true
      advancedlobby.admin: true
      advancedlobby.chatclear.bypass: true
      advancedlobby.globalmute.bypass: true
      advancedlobby.player_hider.bypass: true
      advancedlobby.shield.bypass: true
      advancedlobby.silentlobby: true
      advancedlobby.shield: true
      advancedlobby.custom_item: true
      advancedlobby.chatcolor: true

  advancedlobby.admin:
    description: ''

  advancedlobby.commands.build:
    description: ''
  advancedlobby.commands.chatclear:
    description: ''
  advancedlobby.commands.fly:
    description: ''
  advancedlobby.commands.gamemode:
    description: ''
  advancedlobby.commands.globalmute:
    description: ''
  advancedlobby.commands.teleportall:
    description: ''
  advancedlobby.commands.*:
    description: ''
    children:
      advancedlobby.commands.build: true
      advancedlobby.commands.chatclear: true
      advancedlobby.commands.fly: true
      advancedlobby.commands.gamemode: true
      advancedlobby.commands.globalmute: true
      advancedlobby.commands.teleportall: true

  advancedlobby.chatclear.bypass:
    description: ''
  advancedlobby.globalmute.bypass:
    description: ''
  advancedlobby.player_hider.bypass:
    description: ''
  advancedlobby.silentlobby:
    description: ''
  advancedlobby.shield:
    description: ''
  advancedlobby.shield.bypass:
    description: ''
  advancedlobby.custom_item:
    description: ''
  advancedlobby.chatcolor:
    description: ''

  advancedlobby.cosmetics.*:
    description: ''
    children:
      advancedlobby.cosmetics.hats.*: true
      advancedlobby.cosmetics.particles.*: true
      advancedlobby.cosmetics.balloons.*: true
      advancedlobby.cosmetics.gadgets.*: true

  advancedlobby.cosmetics.hats.melon:
    description: ''
  advancedlobby.cosmetics.hats.tnt:
    description: ''
  advancedlobby.cosmetics.hats.glass:
    description: ''
  advancedlobby.cosmetics.hats.sponge:
    description: ''
  advancedlobby.cosmetics.hats.pumpkin:
    description: ''
  advancedlobby.cosmetics.hats.cactus:
    description: ''
  advancedlobby.cosmetics.hats.*:
    description: ''
    children:
      advancedlobby.cosmetics.hats.melon: true
      advancedlobby.cosmetics.hats.tnt: true
      advancedlobby.cosmetics.hats.glass: true
      advancedlobby.cosmetics.hats.sponge: true
      advancedlobby.cosmetics.hats.pumpkin: true
      advancedlobby.cosmetics.hats.cactus: true


  advancedlobby.cosmetics.particles.heart:
    description: ''
  advancedlobby.cosmetics.particles.music:
    description: ''
  advancedlobby.cosmetics.particles.flames:
    description: ''
  advancedlobby.cosmetics.particles.villager:
    description: ''
  advancedlobby.cosmetics.particles.rainbow:
    description: ''
  advancedlobby.cosmetics.particles.*:
    description: ''
    children:
      advancedlobby.cosmetics.particles.heart: true
      advancedlobby.cosmetics.particles.music: true
      advancedlobby.cosmetics.particles.flames: true
      advancedlobby.cosmetics.particles.villager: true
      advancedlobby.cosmetics.particles.rainbow: true

  advancedlobby.cosmetics.balloons.yellow:
    description: ''
  advancedlobby.cosmetics.balloons.red:
    description: ''
  advancedlobby.cosmetics.balloons.green:
    description: ''
  advancedlobby.cosmetics.balloons.blue:
    description: ''
  advancedlobby.cosmetics.balloons.hay_block:
    description: ''
  advancedlobby.cosmetics.balloons.sea_lantern:
    description: ''
  advancedlobby.cosmetics.balloons.bookshelf:
    description: ''
  advancedlobby.cosmetics.balloons.note_block:
    description: ''
  advancedlobby.cosmetics.balloons.*:
    description: ''
    children:
      advancedlobby.cosmetics.balloons.yellow: true
      advancedlobby.cosmetics.balloons.red: true
      advancedlobby.cosmetics.balloons.green: true
      advancedlobby.cosmetics.balloons.blue: true
      advancedlobby.cosmetics.balloons.hay_block: true
      advancedlobby.cosmetics.balloons.sea_lantern: true
      advancedlobby.cosmetics.balloons.bookshelf: true
      advancedlobby.cosmetics.balloons.note_block: true

  advancedlobby.cosmetics.gadgets.grappling_hook:
    description: ''
  advancedlobby.cosmetics.gadgets.rocket_jump:
    description: ''
  advancedlobby.cosmetics.gadgets.*:
    description: ''
    children:
      advancedlobby.cosmetics.gadgets.grappling_hook: true
      advancedlobby.cosmetics.gadgets.rocket_jump: true
